### PR TITLE
Added a 'Cancel' button to the left of 'Submit' button in the 'Change Password' dialog box.

### LINKED ISSUE #64: Add a cancel button to the “change password” alert box.
## Description
As a user, I need a cancel button on change password alert box which can take me back if I prefer not to change my password.

## Screenshots of the issue
Screenshot_2020-05-13-23-26-44-77_92746fe779a9c2c81c5c767d4a402904

## Acceptance Criteria
- [ ] Include a cancel button left to submit button

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by ghost**
### Description
Added a 'cancel' button on the left of 'submit' button in the 'change password' dialog box. 

Fixes #64

### Flutter Channel:
-  I have used the Flutter Beta channel on my local machine 

### Type of Change:
- Code
- User Interface

**Code/Quality Assurance Only**
Bug fix (non-breaking change which fixes an issue)
This change requires a documentation update (software upgrade on readme file)
New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
On clicking the 'cancel' button, the dialog box closes and the changes made to the password are discarded. 

### Checklist:

My PR follows the style guidelines of this project
I have performed a self-review of my own code or materials
I have commented my code or provided relevant documentation, particularly in hard-to-understand areas.

**Code/Quality Assurance Only**
My changes generate no new warnings
cancel_button

### CODE REVIEW

**Comment by ghost** [comment]
@HaripriyaB , @isabelcosta , @bartekpacia .
Please review. :)

**Comment by HaripriyaB** [comment]
@MaheKhan there is something wrong in the commits. I'm wondering how did all the previous commits of the repo came in to this PR. @Techno-Disaster @bartekpacia pls check this coz I'm confused looking at this!

**Comment by ghost** [comment]
> @MaheKhan there is something wrong in the commits. I'm wondering how did all the previous commits of the repo came in to this PR. @Techno-Disaster @bartekpacia pls check this coz I'm confused looking at this!

oh, yes. I just saw. 
I don't know. 
Yes, @Techno-Disaster , @bartekpacia , please help.

**Comment by HaripriyaB** [comment]
I think it's because you haven't pulled the repo to Ur local branch? Not sure

**Comment by techno-disaster** [comment]
@MaheKhan looks like you are comparing the fork with master branch. change it to develop .
also you might have to use a different fork branch coz u already have a PR running on ur develop fork branch.

**Comment by techno-disaster** [comment]
Closing PR 
Reason : Issue was a First Timer only

**Pull request closed without merging**
