### PR TITLE
Add Reporting Guidelines

### PR DESCRIPTION
**Pull request by techno-disaster**

### CODE REVIEW

**Comment by isabelcosta** [comment]
@Techno-Disaster this is because you are the author of the PR. You have maintained level access. You just have to request review from other maintainers as myself and @bartekpacia .
Also, the PR does not follow the template, probably the template is not set well on the repo, because when you create a PR it should come auto-filled.

**Review by bartekpacia — DISMISSED** [review]

**Comment by isabelcosta** [comment]
Also, I changed the settings for allowing "Squash & Merge" option as other Mentorship projects, since this is also a community guideline of ours. You can see that you have too many commits here that could be reduced to one right? This also tags the PR in the commit right away.

**Review by isabelcosta — COMMENTED** [review]
Why @Techno-Disaster  is this inside REPORTING_GUIDELINES folder instead of just `.github`?

**Comment by techno-disaster** [comment]
@isabelcosta we can auto request review from people whom we add in the CODEOWNERS file, you can read about it here https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
do you want me to add this? it will be convinent to just make a PR and auto request review from people mentioned in the owners file

also yes i did not see the pull request template option i will fix this asap

**Comment by techno-disaster** [comment]
> Why @Techno-Disaster is this inside REPORTING_GUIDELINES folder instead of just `.github`?

imo it looks a bit more clean.

**Comment by isabelcosta** [comment]
> > Why @Techno-Disaster is this inside REPORTING_GUIDELINES folder instead of just `.github`?
> 
> imo it looks a bit more clean.

imo it seems too deep of a folder structure. So I think it makes sense to create a folder when you have more than one file to put there. Example:
- if we have only one pull request template, putting just on .github folder makes sense.
- if you have more than one issue template, it makes sense to put into an issue template folder.

What do you think @Techno-Disaster @bartekpacia ?

**Comment by techno-disaster** [comment]
@isabelcosta  squashed

**Comment by techno-disaster** [comment]
ok no i messed up git sorry, will fix it asap

**Comment by isabelcosta** [comment]
messing up git is part of every developer journey 🙃

**Pull request closed without merging**
