### PR TITLE
feat: Maintenance update

### LINKED ISSUE #60: Add links to Terms, Policy and CoC on Sign Up screen
## Description

As a user of the system,
I need to have links to terms and conditions on Register screen
so that I can be aware of Terms of use, Code of Conduct and Privacy Policy.

On Registration Screen we need to have a proper text with the Terms and Conditions check box.

Text:

"By checking this box, I affirm that I have read and accept to be bound by the AnitaB.org Code of Conduct, Terms, and Privacy Policy. Further, I consent to the use of my information for the stated purpose."

Links to add:

Code of Conduct: https://ghc.anitab.org/code-of-conduct/
Terms of use: https://anitab.org/terms-of-use/
Privacy Policy: https://anitab.org/privacy-policy/

## Screenshots of the issue

Android version:

image

Flutter current version:

image

### Update [Required]
- [ ] Add links to Terms and Conditions, Code of Conduct and Privacy Policy on Sign Up screen

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
🤷‍♀️

### LINKED ISSUE #64: Add a cancel button to the “change password” alert box.
## Description
As a user, I need a cancel button on change password alert box which can take me back if I prefer not to change my password.

## Screenshots of the issue
Screenshot_2020-05-13-23-26-44-77_92746fe779a9c2c81c5c767d4a402904

## Acceptance Criteria
- [ ] Include a cancel button left to submit button

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### LINKED ISSUE #96: Add mark as done comfirmation dialog when clicked on checkbox of a task
**Is your feature request related to a problem? Please describe.**
When  user clicks on the checkbox of task, it directly marks as done without confirming the user.

**Describe the solution you'd like**
Show a dialog box when a task is checked by the user. Like the one in android version.

**Additional context**
Android version:
Record-2020-06-11-18-08-40-184af

Flutter version:
Record-2020-06-11-17-51-03-92746

### LINKED ISSUE #97: Maintainance.
### Issue
We have some issues piling up, so as per May's instructions, this issue consists of several first timer and other simpler issues combined. These are the issues you need to work on: 
#60 #63 #64 #96
Each of the above issue  already has a well defined body which tells what the issue is about, refer that when you are working on that issue.

### Definition of Done
- [x] #60 
- [ ] #63 
- [x] #64 
- [x]  #96

### PR DESCRIPTION
**Pull request by techno-disaster**
### Description

Maintenance update

**Changes:**

- Don't track generated files
- Add links to Terms, Policy and CoC on Sign Up screen
- Add a cancel button to the “change password” alert box
- Add mark as done comfirmation dialog when clicked on checkbox of a task

Fixes #97 
Fixes #60 
Fixes #64 
Fixes #96 

### Type of Change:

- Maintainance

### How Has This Been Tested?
Physical device :)

#### New UI Screenshots:

| column 1 | column 2 |
|-|-|
| 85538862-eb44dc00-b632-11ea-8bfe-1697f98a60e0 | 85538874-eda73600-b632-11ea-8dc2-4ea79e7fa930 | 
| 85538884-ef70f980-b632-11ea-8b84-a09ca39b14dc | 85538897-f13abd00-b632-11ea-9c44-fb663fd3752a | 

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by techno-disaster** [comment]
I have not added #63 yet because I'm not sure if we should move forward with these changes. The current QA team might face some problems and will have to change their workflow to test PRs and imho, these files aren't really that big. Also i would like to point out these files are not ```node_modules``` as mentioned in #63  issue body, these are simply generated files by dependencies and afaik node_modules are the dependencies itself. 

If we do add #63 we would have to change the docs, ci, and update the qa team which imo is not really necessary as the current workflow might get disrupted and it's not really worth it? What do you think @bartekpacia @isabelcosta 
cc: @anitab-org/qa-team

**Comment by techno-disaster** [comment]
@anitab-org/qa-team can someone test this PR? 
Thank You

**Review by isabelcosta — CHANGES_REQUESTED** [review]
@Techno-Disaster can you please include in the PR description a description for every issue you solved. It can be a bit too much having to check each issue to understand what are the features/fixes being done here.
Also, I see you updated the user interface of the app with your code, could you include screenshots of it in the PR description as well.

**Comment by techno-disaster** [comment]
> @Techno-Disaster can you please include in the PR description a description for every issue you solved. It can be a bit too much having to check each issue to understand what are the features/fixes being done here.
> Also, I see you updated the user interface of the app with your code, could you include screenshots of it in the PR description as well.

@isabelcosta i updated the issue body and fixed the conflicts can you check now?
cc: @bartekpacia

**Comment by isabelcosta** [comment]
@Techno-Disaster can you you just make a bulleted list of the changes, like:
- added hyperlink to terms and conditions copy on Sign Up
- fixes X bug
- etc

The description is overwhelming to read, the images are already in the issues so they don't need to be in the PR description 🙈

**Comment by isabelcosta** [comment]
@Techno-Disaster I edited part of it. There is one issue you don't have a check in the Maintainance Issue, isn't that done here? the "Don't track generated files"?

**Comment by techno-disaster** [comment]
@isabelcosta yes i mentioned that [here](https://github.com/anitab-org/mentorship-flutter/pull/103#issuecomment-647046746) Can you take a look? cc: @bartekpacia

**Review by bartekpacia — APPROVED** [review]
GJ

**Comment by isabelcosta** [comment]
> @isabelcosta yes i mentioned that [here](https://github.com/anitab-org/mentorship-flutter/pull/103#issuecomment-647046746) Can you take a look? cc: @bartekpacia

thank you for mentioning this. Sounds good :) @Techno-Disaster

**Comment by isabelcosta** [comment]
@Techno-Disaster can you add images / GIFs to the PR, of your visual changes?

**Comment by techno-disaster** [comment]
> @Techno-Disaster can you add images / GIFs to the PR, of your visual changes?

sure, done. I had added them earlier but you removed them by mistake i guess

Sounds good @Techno-Disaster ! I removed sort of by mistake, because you added the descriptions of the issues fully, so it was very very confusing. And the images are sooo huge 🙈  I'll edit it soon, but I will also approve this.

**Review by isabelcosta — APPROVED** [review]
Great work @Techno-Disaster thank you for doing all these issues 👏

**Pull request merged**
