### PR TITLE
docs: Add Travis Build Badge

### LINKED ISSUE #47: Add Travis Build Badge
**Is your feature request related to a problem? Please describe.**
Follow the other AnitaB repos style and add a travis build status badge in readme
**Describe the solution you'd like**
Add the badge, you can refer to [this article](https://docs.travis-ci.com/user/status-images/) to do this.

PS : someone should start working on the documentation issue template issue #26 .This template does not feel right for this issue

### PR DESCRIPTION
**Pull request by gaurivn**
### Description
Added Travis Build Badge.

Fixes #47 

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**

- Documentation

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Great work @gaurivn 🎉 
Thank you so much for your contribution :)

**Comment by gaurivn** [comment]
Thank you @isabelcosta

**Review by techno-disaster — APPROVED** [review]
looks good

**Comment by techno-disaster** [comment]
oh wait i did not see the master branch sorry. We won't be using it. Should i revert this merge @isabelcosta ?

**Comment by isabelcosta** [comment]
No problem I did not notice either. You can just create an issue and fix that, it does not seem like a dangerous change :) @Techno-Disaster do you agree with this solution?

**Comment by techno-disaster** [comment]
> No problem I did not notice either. You can just create an issue and fix that, it does not seem like a dangerous change :) @Techno-Disaster do you agree with this solution?

sure. reverting can mess up git according to my experience. Should i make a issue or can i just send a PR? seems like a really small change :)

**Comment by isabelcosta** [comment]
Can you create an issue plzzzz, and your issues are quite short, so I see no problem in creating an issue, and claim it there, then submitting a PR, to keep track of the why, you are fixing something that came from this PR. I promise to be quick to review 🙃  @Techno-Disaster

**Comment by techno-disaster** [comment]
> Can you create an issue plzzzz, and your issues are quite short, so I see no problem in creating an issue, and claim it there, then submitting a PR, to keep track of the why, you are fixing something that came from this PR. I promise to be quick to review upside_down_face @Techno-Disaster

ah yes sure, I shoudn't be lazy + i will try to be more descriptive in my PRs @isabelcosta. will do it asap

**Pull request merged**
