### PR TITLE
Excluded unneeded files from git

### LINKED ISSUE #63: Don't track generated files
**Describe the problem**
Some of the code in this project(boilerplate to communicate with the API) is generated using [chopper](https://pub.dev/packages/chopper) package. This isn't a good practice, because generated code shouldn't be included under VCS like Git (for those who have experience with JS, it's like including `node_modules`).

Photo example:
Screenshot 2020-05-12 at 11 53 23 PM

**Expected behavior**
Generated files, i.e those with `chopper` in their names, should be excluded (= added to the `.gitignore`) and removed from Git.

### PR DESCRIPTION
**Pull request by bartekpacia**
### Description
Generally, files that are generated shouldn't be included under version control system like `git`.
In this little PR, I removed those files. (I tried to write a descriptive commit message, so you can take a look at it).

The only change worth mentioning is that people who `git clone` this repo for the first time will have to generate those files manually. I included instructions explaining how to do this in the README.

Fixes #63.

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
- Documentation

### How Has This Been Tested?
Doesn't affect anything.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by techno-disaster** [comment]
looks like i might have to add ```flutter pub run build_runner build``` to the ci too, any other commands required @bartekpacia ?

**Comment by bartekpacia** [comment]
@Techno-Disaster Yes, without it, it'll fail.

**Comment by techno-disaster** [comment]
missed this earlier but @bartekpacia  doesn't this fix #63 ?

**Comment by bartekpacia** [comment]
Yep, it does. I forgot to mention it, sorry.

**Comment by techno-disaster** [comment]
Hey @bartekpacia  you might want to read  [this](https://github.com/anitab-org/mentorship-flutter/issues/64) discussion, seeing that it is a first timer issue 🙈.

**Comment by mayburgos** [comment]
I'm going to close this PR to give First Timers a chance to contribute to this. However, can you two reach out to others who have shown interest in contributing? 

Here are some people I know interested in Flutter: 
Akanksha Singh
Haripriya
Kavya
NANDINI goyal
Rasika Kedia
Sanika Ratnaparkhi

I don't know if they've contributed, but let's reach out to them (First Timers to Flutter) to solve this issue.

**Pull request closed without merging**
