### PR TITLE
fix: update relationship toggles

### LINKED ISSUE #27: Finish ProfilePage implementation
**Is your feature request related to a problem? Please describe.**
Currently changing `available to mentor` and `needs mentoring` on the **RelationPage** doesn't have any effect.

demo

**Describe the solution you'd like**
I'd like this to work. I'd love this to work and be nicely coded :)

**Additional context**
I remember I had some issues with this while speed-coding this app during GCI and finally forgot to finish this :) That's why it isn't already implemented.

### PR DESCRIPTION
**Pull request by techno-disaster**
### Description
Fix the relationship toggles on profile page. Previously these buttons weren't implemented. Also i would like to thank @gaurav192 again for helping me with this PR. This page will look a lot better ones #67  is also merged to show the loading indicator when "save profile" button is clicked

Fixes #27 

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Physical Device.
Steps to test: 
Go to profile page and try to edit the available to mentor and need mentoring toggles
ezgif com-video-to-gif

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by bartekpacia — APPROVED** [review]
Great job!

**Comment by techno-disaster** [comment]
@anitab-org/qa-team can anyone test this?
Steps to test:
Go to profile page and try to edit the available to mentor and need mentoring toggles

**Review by foongminwong — APPROVED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done by @bartekpacia 

2. All possible responses were tested as below:

  * _Before PR 91_  

    _Screenshot/gif/url_:  before-pr-91

    _Expected Result_:  Unable to edit the relationship toggles.
    _Actual Result_: Same as above

  * _After PR 91_  

    _Screenshot/gif/url_:  after-pr-91

    _Expected Result_:  Able to edit the relationship toggles.
    _Actual Result_:  Same as above

3. Additional testcases covered: N/A
    
4. Additional Comments: N/A

5. Status of PR Changed to: Remove `Needs Testing`

6. Android Version: 9.0, Device: Android Emulator Pixel API 28

**Comment by techno-disaster** [comment]
@foongminwong thanks a lot, your testing never fails to impress :see_no_evil: 
@isabelcosta I think we can merge this now :) can you take a quick look? Thank You

**Review by robotjellyzone — APPROVED** [review]
Everything looks good to me @Techno-Disaster !! Just a slight doubt about using slack as since no slack is currently in use so, what slack name one could use in his/her profile ?

**Comment by techno-disaster** [comment]
> Everything looks good to me @Techno-Disaster !! Just a slight doubt about using slack as since no slack is currently in use so, what slack name one could use in his/her profile ?

We currently have no "third party" login methods. So the slack is just a placeholder

**Review by HaripriyaB — APPROVED** [review]

**Review by bartekpacia — APPROVED** [review]
looks good to me

**Review by isabelcosta — APPROVED** [review]
Seems good to me as well!
Thank you @Techno-Disaster for contributing with this 🎉 
Thank you @foongminwong for your amazing test report 🙌

**Pull request merged**
