### PR TITLE
feat: Integrate Travis CI

### LINKED ISSUE #13: Publish app under Releases
**Is your feature request related to a problem? Please describe.**
Once the app is built by the github action, we have to publish it under the releases tab for users without flutter to try out the app

**Describe the solution you'd like**
Once the app is built publish it under the releases tab of the repo

**Describe alternatives you've considered**
We could try Travis but i think we can do the same with the existing workflow itself

### PR DESCRIPTION
**Pull request by techno-disaster**
### Description
Integrate Travis CI to let users test progress without building the app themselves, this follows the same style as CI to push apps to a new branch as mentorship-android. So now we have github actions to check building on PR, the checks show right below the PR and once we approve them and merge them to develop branch travis will build the app and push it to the apk branch

Fixes #13 

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
- CI/CD

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
my repo : https://github.com/Techno-Disaster/mentorship-flutter/tree/develop
app pushed by travis: https://github.com/Techno-Disaster/mentorship-flutter/tree/apk
travis log: https://travis-ci.com/github/Techno-Disaster/mentorship-flutter/builds/160930369

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by techno-disaster** [comment]
should have squashed :(

**Comment by isabelcosta** [comment]
> should have squashed :(

no problem since the option available here for merge is "Squash & Merge" ;)

**Review by bartekpacia — APPROVED** [review]
looks good!

**Comment by techno-disaster** [comment]
@isabelcosta Anna informed me that the github_api_token key was added in travis, any other changes required? If not can we merge this? 
Thank You
cc: @annabauza

**Review by isabelcosta — APPROVED** [review]
Based on your comment @Techno-Disaster I'll approve this ;)
Feel free to merge it and see if everything is fine

**Comment by techno-disaster** [comment]
We are good to go  @isabelcosta 
you can now test the app from https://github.com/anitab-org/mentorship-flutter/tree/apk

**Pull request merged**
