### PR TITLE
Add reporting guidelines and fix pull request template

### PR DESCRIPTION
**Pull request by techno-disaster**
Issue : #3

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]

**Comment by isabelcosta** [comment]
@Techno-Disaster I put the rule for 2 minimum required reviews. Is this not working? I am asking because @bartekpacia hasn't approved yet, so I was wondering how that was possible because you were the one asking for the 2 minimum reviews and I thought I had applied that.
cc @mayburgos @annabauza did I set something wrong 🤔

**Comment by techno-disaster** [comment]
@isabelcosta No i was testing if the PR template works and hence merged this using administrative merge as this was a straight forward PR, but i am a bit confused with git right now, i did merge this but when i create a new PR i still do not get the template. If you are free can you check why this is happening? 
Thank You

**Comment by techno-disaster** [comment]
@isabelcosta are we allowed to do squash and merge i am not sure how we move forward with merging PRs here and i might have made a mistake with merging this myself sorry

**Comment by isabelcosta** [comment]
> @isabelcosta are we allowed to do squash and merge i am not sure how we move forward with merging PRs here and i might have made a mistake with merging this myself sorry

I only enabled the "Squash and Merge" so I would say you don't need to squash on your branch, you can just do squash and merge on GitHub interface. that way we avoid mistakes with git push and things like that

**Comment by isabelcosta** [comment]
> @isabelcosta No i was testing if the PR template works and hence merged this using administrative merge as this was a straight forward PR, but i am a bit confused with git right now, i did merge this but when i create a new PR i still do not get the template. If you are free can you check why this is happening?
> Thank You

Ah okay, you can do that because you have "Maintain" level access. I know this case was very simple, but we should avoid this, there was no problem in waiting a bit. I just want to make sure that we are careful with our judgement of what a "straight forward PR" means. Please avoid doing that when is code related. @Techno-Disaster

**Comment by techno-disaster** [comment]
@isabelcosta yes, this won't happen again.Also i think i know why the pull request template isn't working. I checked the mentorship android app and i think that the template name has to be in all Caps -> PULL_REQUEST_TEMPLATE.md. Do you think this will fix it?

**Comment by isabelcosta** [comment]
@Techno-Disaster no problem, it's just that code is subjective, I understand that you did this with the guidelines :)
About the pull request https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template, I am not sure that is the problem. But we can try.

**Comment by isabelcosta** [comment]
@Techno-Disaster I think the change you did in this PR will work as it is :) because now the `develop` branch is the default, I'm sure the next PR will use the template ;)

**Pull request merged**
