### PR TITLE
Update gh action

### LINKED ISSUE #127: feat: easier testing and cleaner flutter ci
**Is your feature request related to a problem? Please describe.**
QA testers gave to download flutter just to test a small apk. We should be able to do this without an emulator or installing flutter on the qa team member's device

**Describe the solution you'd like**
Upload the apk for each PR to github artifacts which can be downloaded by the qa team to make their testing easier. So basically the tester from qa team will not have to use an android emulator or install flutter to test PRs on this repo anymore. Just download the artifact from below each PR :)

### PR DESCRIPTION
**Pull request by techno-disaster**
### Description
This ci does whatever the previous ci (cleaner code tho) did but it additionally uploads the apk for each PR to github artifacts which can be donwloaded by the qa team to make their testing easier. So basically the tester from qa team will not have to use an android emulator or install flutter to test PRs on this repo anymore. Just download the artifact from below each PR :)

Fixes #127 

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**

- Quality Assurance

**Code/Quality Assurance Only**

- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
image

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by HaripriyaB — DISMISSED** [review]

**Comment by isabelcosta** [comment]
@Techno-Disaster can you solve the merge conflict and then I can approve and merge this?

**Comment by techno-disaster** [comment]
@anitab-org/mentorship-flutter-maintainers done :)

**Review by isabelcosta — APPROVED** [review]
Thank you @Techno-Disaster this is amazing! I can't wait to see this in the works

**Review by robotjellyzone — APPROVED** [review]
Hmm... amazing work @Techno-Disaster 🎉 👍 .....

**Pull request merged**
