### PR TITLE
feat: make disabled text fields appear grey on profile page

### LINKED ISSUE #84: Make disabled textfields grey on profile page
**Is your feature request related to a problem? Please describe.**
Currently there is no difference in the profile page when editing is on or off. 

**Describe the solution you'd like**
I would like the profile page to be greyed out (suggesting that it is disabled), if i haven't selected editing mode to be on. 

**Additional context**

| Android version (how it should be) | Flutter Version (how it is) |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| Screenshot_20200522-100401123 | Screenshot_20200522-100416214 |

### PR DESCRIPTION
**Pull request by bharat-1809**
### Description
Added an opacity widget that sets the opacity of the page to 50% when editing is disabled and changes to 100% when editing is enabled.

Fixes #84 

### Flutter Channel:
- [ ] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Physical device.
Steps:
- Go to the profile page by selecting it from bottom bar
- Click on the Floating Action Button to start editing and see the changes

sample

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by bartekpacia** [comment]
Looks cool! It'd be even nicer if you added some simple animation to it, what do you think @bharat-1809?

**Comment by techno-disaster** [comment]
> Looks cool! It'd be even nicer if you added some simple animation to it, what do you think @bharat-1809?

@bartekpacia  what kind of animation are we talking about? because we already have #83  which adds loading indicators.

**Comment by bartekpacia** [comment]
Sorry for not specifying; I mean fading the opacity.

**Comment by bharat-1809** [comment]
@bartekpacia sure, I'll start working on it :)

**Comment by bartekpacia** [comment]
Thank you, it'll look and feel better this way:)

PS If you don't feel like doing it, just write, I'll accept this because it's already great work.

**Comment by bharat-1809** [comment]
@bartekpacia Thanks ☺, I have no problem in doing it and would love to contribute :))
Thanks again.

**Comment by techno-disaster** [comment]
Hey, @bharat-1809  any updates?

**Comment by bharat-1809** [comment]
@Techno-Disaster  Sorry for the delay, I will make the changes surely by tonight.

**Comment by bharat-1809** [comment]
I have added the fading animation. Please have a look and suggest any changes if required.
Thanks :)

**Comment by bartekpacia** [comment]
This looks great, thank you!:D

**Review by bartekpacia — APPROVED** [review]

**Review by robotjellyzone — APPROVED** [review]
I have reviwed & tested this PR , and its working fine as it should 👍 .

tested_pr

**Comment by isabelcosta** [comment]
@Techno-Disaster can you please review and approve if you feel it should be.

**Review by techno-disaster — APPROVED** [review]
LGTM, goof work :)

**Pull request merged**
