### PR TITLE
Add Action to build app on PR

### LINKED ISSUE #4: Create Code of Conduct
**Is your feature request related to a problem?**

As a project within AnitaB.org Open Source Community, we need a code of conduct in the repository.

**Describe the solution you'd like**

The code of conduct should be the same as in every repo. Here is is the update one: https://github.com/anitab-org/anitab-org.github.io/blob/develop/code_of_conduct.md

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### LINKED ISSUE #8: Create Github Action
**Is your feature request related to a problem? Please describe.**
Adding this github action will make sure that none of the PRs include any changes which will break the app.

**Describe the solution you'd like**
Build a Github Action which will trigger a workflow to build an app on IOS and Android everytime we recieve a Pull Request

**Describe alternatives you've considered**
I have considered Travis CI but imho github action was the easiest to implement and has good integration with github itself

**Additional context**

### PR DESCRIPTION
**Pull request by techno-disaster**
@isabelcosta  seems like the pull request template is still now working, any idea why?
Closes #8 
this PR  includes the workflow file, so we once this is accepted github will build a PR every PR as shown in the screenshots below
action1
action2

### CODE REVIEW

**Review by bartekpacia — DISMISSED** [review]

**Comment by bartekpacia** [comment]
nice job

**Review by isabelcosta — DISMISSED** [review]
@Techno-Disaster Can you please separate the code of conduct PR from the GitHub actions, it seems misplaced. Can you do another PR just about the code of conduct, since these are different things :/ ? Its good to have PRs with separate concerns, we encourage this in our community.

**Comment by techno-disaster** [comment]
> @Techno-Disaster Can you please separate the code of conduct PR from the GitHub actions, it seems misplaced. Can you do another PR just about the code of conduct, since these are different things :/ ? Its good to have PRs with separate concerns, we encourage this in our community.

so that would mean first I'll have to make one of the PR and then when thats accepted make the second PR? just confirming if there is any alternative way to split a PR

**Comment by isabelcosta** [comment]
> > @Techno-Disaster Can you please separate the code of conduct PR from the GitHub actions, it seems misplaced. Can you do another PR just about the code of conduct, since these are different things :/ ? Its good to have PRs with separate concerns, we encourage this in our community.
> 
> so that would mean first I'll have to make one of the PR and then when thats accepted make the second PR? just confirming if there is any alternative way to split a PR

you can do 2 PRs at the same time, and we review them on separate occasions :) You can just remove the code of conduct markdown from this PR and then create another PR for code of conduct :) you can even leave this for other contributors (first timers only), while you concentrate on this maintenance stuff. What do you think? @Techno-Disaster

**Comment by isabelcosta** [comment]
Can you also create an issue for GitHub action? and then link it in this PR instead of linking the code of conduct one?

**Comment by techno-disaster** [comment]
@isabelcosta sounds good, i have deleted the code of conduct now and this is the PR only for the workflow action

**Review by bartekpacia — APPROVED** [review]

**Comment by techno-disaster** [comment]
@isabelcosta  i have added a new issue and linked it to this.

**Review by isabelcosta — APPROVED** [review]
Cool, I don't quite understand how GitHub actions work, will approve to help you test this.
Just a suggestion: It would be nice if you would ask on Zulip for a second opinion, perhaps someone knows about GitHub actions and could give a review :)

**Comment by techno-disaster** [comment]
> Cool, I don't quite understand how GitHub actions work, will approve to help you test this.
> Just a suggestion: It would be nice if you would ask on Zulip for a second opinion, perhaps someone knows about GitHub actions and could give a review :)

Sure, @isabelcosta if you want to know more about github actions [this](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions) explains it really well. Also i have made a thread in Zulip general/GithubAction to see if someone has any suggestions for this PR.Will merge it after that, thank you

**Comment by isabelcosta** [comment]
Thank you for sending the resource, I will take a look into. @Techno-Disaster

**Pull request merged**
