### PR TITLE
Fix for #134 delete account button removed

### LINKED ISSUE #134: Remove delete account button
**Is your feature request related to a problem? Please describe.**
We don't want to allow the user to delete his/her account as it messes the db at the backend.

**Describe the solution you'd like**
Remove the delete account option from the UI from the settings page

### PR DESCRIPTION
**Pull request by HaripriyaB**
### Description
The delete account button is removed from UI.

Fixes #134 

### Flutter Channel:
- [X] I have used the Flutter Beta channel on my local machine 

### Type of Change:
- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Before:

After

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by techno-disaster — APPROVED** [review]
LGTM

**Review by isabelcosta — APPROVED** [review]
Great work @HaripriyaB 👏

**Comment by isabelcosta** [comment]
@anitab-org/qa-team can anyone please test this PR?

**Comment by isabelcosta** [comment]
@Techno-Disaster have you tested this PR locally, if you have just put a print here in a comment and then you can merge this, you have access to :)

**Comment by techno-disaster** [comment]
@isabelcosta  sure. FYI you can test this easily too. The apk is uploaded in the artifacts section. 
https://github.com/anitab-org/mentorship-flutter/pull/135/checks   this happens for each PR

**Comment by techno-disaster** [comment]
Screenshot_20200904-082546
Tested locally

**Pull request merged**
