### PR TITLE
feat: search members

### LINKED ISSUE #38: MembersPage: add search feature
**Is your feature request related to a problem?**
Currently the searching functionality in the [MembersPage](https://github.com/anitab-org/mentorship-flutter/blob/develop/lib/screens/home/pages/members/members_page.dart) doesn't work.

**Describe the solution you'd like**
Adding the search feature like in [the Android app](https://github.com/anitab-org/mentorship-android).

A final solution should preferably use BLoC pattern (like the rest of the app). I'm not quite sure how it would look like, *so the person who will be doing it*: implement it so that it will just work and we will iterate on it & improve.

### PR DESCRIPTION
**Pull request by techno-disaster**
### Description
Let other users search mentors and mentees using the search functionality :)

Fixes #38 

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**

- User Interface

### How Has This Been Tested?
Physical device. Adding video below 
ezgif com-video-to-gif

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by techno-disaster** [comment]
@anitab-org/qa-team can someone give this a quick test?

**Review by HaripriyaB — APPROVED** [review]
Good job 👍

**Comment by Akanksha1212** [comment]
Great work! @Techno-Disaster

**Review by robotjellyzone — APPROVED** [review]
I have tested this pr and its working in the way it should 👍 

The changes made in this PR were tested locally. Following are the results:

1. Code Review: Done

2. All possible responses were tested as below:
Screenshot/gif:
tested-pr-gif

Expected Result: Search members by their name in the search bar
Actual Result: Same as above

3. Additional testcases covered: n/a

**Review by robotjellyzone — COMMENTED** [review]
Just a suggestion @Techno-Disaster, i think it would be great if you can add this search functionality to that search symbol which is there on the right of the **Members** tab [and left of the settings button].  So that on just clicking that symbol at the top, one can directly do the searching of members.

**Comment by techno-disaster** [comment]
@robotjellyzone yes, I planned to do that before but if you check mentorship-androod repo it was decided to have a new page for search functionality. This helps in UX.

**Comment by rpattath** [comment]
@robotjellyzone would you mind adding this test to [TestQuality](https://anitab-org.testquality.com/signup). Ping me if you need help.

**Review by isabelcosta — APPROVED** [review]
Looks good!

**Comment by isabelcosta** [comment]
I'll merge this, I understand that @bartekpacia is busy these days. If you find anything that should be improved in this PR please raise an issue or let us know somehow (e.g.: Zulip).

**Pull request merged**
