### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by techno-disaster**
### Description
Update dependencies and put ```beta``` in github action instead of hardcoding flutter version

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### How has this been tested?
Logs with these changes can be found [here](https://github.com/Techno-Disaster/mentorship-flutter/actions/runs/137132381)

### Type of Change:
**Delete irrelevant options.**

- Quality Assurance

### CODE REVIEW

**Comment by bartekpacia** [comment]
Won't it create non-deterministic builds?

Also: commit squashing ;P

**Comment by techno-disaster** [comment]
> Won't it create non-deterministic builds?
> 
> Also: commit squashing ;P

I'm not sure what non-deterministic builds are ? 
also we have squash and merge enabled ;)

**Comment by bartekpacia** [comment]
I mean that the Flutter version we're using should be explicitly defined.
The project might work well on your local machine but crash at the CI stage because of different Flutter version.

PS After writing this,  I'm not sure whether it is a good or bad idea. [Non-deterministic builds are a problem on Android when you don't hardcode libraries version](https://docs.gradle.org/current/userguide/dependency_locking.html). This case is slightly similar but also slightly different.

**Comment by techno-disaster** [comment]
> I mean that the Flutter version we're using should be explicitly defined.
> The project might work well on your local machine but crash at the CI stage because of different Flutter version.
> 
> PS After writing this, I'm not sure whether it is a good or bad idea. [Non-deterministic builds are a problem on Android when you don't hardcode libraries version](https://docs.gradle.org/current/userguide/dependency_locking.html). This case is slightly similar but also slightly different.

but if we have already asked contributors to work with the latest flutter beta branch (this is a check in issue template too) , won't the local machine flutter version and beta branch version be the same? Because basically beta channel is cloning the flutter repo and the beta branch.You can check this out [here](https://flutter.dev/docs/get-started/install/linux)

**Comment by bartekpacia** [comment]
We can't assume this, because people often forget to `flutter  upgrade`.

**Comment by techno-disaster** [comment]
> We can't assume this, because people often forget to `flutter upgrade`.

Well in that case, even if we update our CI with hard-coded version number and the contributor hasn't updated it will be the same case right? for example flutter released v2 for beta, and we updated it on the  CI, but the contributor forgot flutter upgrade, this will be the same case as you are saying right? Solution to this could be to just stick with a very old flutter beta build to be sure everyone is on that atleast, but that doesn't make any sense right? So what do you think, how should we handle this?
also the Travis CI has been using the beta branch from the beginning, and we haven't faced any issue with it yet

**Comment by bartekpacia** [comment]
Okay, I think we can try this and see if we'll encounter any problems.

**Review by robotjellyzone — DISMISSED** [review]
@Techno-Disaster  Since these were slight changes so, it Looks good to me 👍 but to check whether these changes are giving required result this needs testing to changing the label to **Testing**  

Also, can you please resolve the merge conflicts? @Techno-Disaster

**Review by bartekpacia — DISMISSED** [review]

**Comment by techno-disaster** [comment]
Thanks for solving the conflict @bartekpacia . Keeping bloc and flutter bloc on version 4.x.x because some changes are required for migrating to 5.x.x , Will do that separately in another PR.
Can someone from @anitab-org/qa-team give this a test? Just the dependencies were updated no new features/ bug fixes

**Review by robotjellyzone — APPROVED** [review]
I have tested every other feature of the app, so, everything is working and nothing is breaking as expected as can be seen from the following gif :

pr-jayesh

great job @Techno-Disaster 👍

**Comment by robotjellyzone** [comment]
Just want to know is **Find Members** feature is not implemented yet ? or maybe I am not aware of it? @Techno-Disaster

**Comment by techno-disaster** [comment]
@robotjellyzone no, search is not implemented yet. But the find members button should take you to the members page when you don't have any prior relations.

**Comment by robotjellyzone** [comment]
> @robotjellyzone no, search is not implemented yet. But the find members button should take you to the members page when you don't have any prior relations.

as you can see @Techno-Disaster  in the provided gif that on clicking **Find Members** , its not taking anywhere? and it should as you say so, may be your pr is behind the parent repo 🤔

**Comment by techno-disaster** [comment]
> > @robotjellyzone no, search is not implemented yet. But the find members button should take you to the members page when you don't have any prior relations.
> 
> as you can see @Techno-Disaster in the provided gif that on clicking **Find Members** , its not taking anywhere? and it should as you say so, may be your pr is behind the parent repo thinking

@robotjellyzone I just checked and this is due to the #108 PR ig, it changes how we do bottom navy. But the fix is not related to this PR. You can approve this and I will create a new issue for this :)

**Comment by techno-disaster** [comment]
Issue up #113

**Review by robotjellyzone — DISMISSED** [review]
Ok @Techno-Disaster i am approving so, that you can create a new issue for that find members issue :)

**Comment by techno-disaster** [comment]
@anitab-org/mentorship-flutter-maintainers can you review this asap?

**Review by isabelcosta — APPROVED** [review]

**Comment by isabelcosta** [comment]
@bartekpacia can you please review this?

**Review by bartekpacia — APPROVED** [review]
LGTM!

**Pull request merged**
