### PR TITLE
Prefer Logger.root over print()

### PR DESCRIPTION
**Pull request by bartekpacia**
### Description
`print()` is fast, but (very!) dirty. We have to manually include all the information that we want, and if we don't, we might end up with the following output in the console:

```
loading data
debug # 2
loaded data
error
debug # 1
fix this in the future
test5
```

Logger is a class from [Dart's official logging package](https://pub.dev/packages/logging). After some initial configuration, it's easy to *log with style*:

```
I/flutter (17106): INFO: 2020-05-18 12:46:08.911003: AppStarted
I/flutter (17106): INFO: 2020-05-18 12:46:11.354172: Has token!
I/flutter (17106): INFO: 2020-05-18 12:46:11.361696: Transition { currentState: AuthUninitialized, event: AppStarted, nextState: AuthAuthenticated }
I/flutter (17106): INFO: 2020-05-18 12:46:11.686906: StatsPageShowed
I/flutter (17106): INFO: 2020-05-18 12:46:11.780145: Transition { currentState: StatsPageInitial, event: StatsPageShowed, nextState: StatsPageLoading }
I/flutter (17106): INFO: 2020-05-18 12:46:11.842777: --> GET https://mentorship-backend-temp.herokuapp.com/home
I/flutter (17106): INFO: 2020-05-18 12:46:11.848238: --> END GET
I/flutter (17106): INFO: 2020-05-18 12:46:11.859703: Has token!
```

I also refactored all uses of `print()` to `Logger.root`.

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
- Code
- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Does not affect business logic.
Everything works fine.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by techno-disaster** [comment]
looks good, although you should make a issue. I know it kinda slows down the contribution speed, but rules are rules 😃. I'll approve now, but please make a issue henceforth, even if its a small change.

**Review by techno-disaster — DISMISSED** [review]
please make an issue. great work 🎉

**Comment by bartekpacia** [comment]
Ahh, I forgot👀
I *promise*, I will create an issue for the next one. (tho I think I gave a good explanation of the issue in he PR description.)

**Review by isabelcosta — DISMISSED** [review]
Looks fine by me :)

**Review by techno-disaster — APPROVED** [review]
LGTM 👀

**Comment by bartekpacia** [comment]
@isabelcosta I'm not sure but you may have forgotten to approve this👀

**Comment by isabelcosta** [comment]
@bartekpacia when you change something after an approval, the approvals get dismissed, so I have to approve again.

**Review by isabelcosta — APPROVED** [review]
Looks good, although I have not tested this out :)

**Comment by isabelcosta** [comment]
@Techno-Disaster did you rin the app, just to make sure nothing broke? Can you do that and mention it here?

**Comment by techno-disaster** [comment]
> @Techno-Disaster did you rin the app, just to make sure nothing broke? Can you do that and mention it here?

No i did not, although the changes seem to be done only to the contribution doc, and in 2 places print has been changed to Logger. I'll still check this and comment here.

**Comment by isabelcosta** [comment]
@Techno-Disaster thank you 🙏

**Comment by techno-disaster** [comment]
Hey, sorry forgot to update here but the changes don't break anything

**Comment by isabelcosta** [comment]
> Hey, sorry forgot to update here but the changes don't break anything

cc @bartekpacia don't forget about the testing phase.

**Comment by bartekpacia** [comment]
@isabelcosta I know, this is a very tiny change but I tested core functionality anyway on the emulator and it worked fine.

**Pull request merged**
