### PR TITLE
feat: add sections in task tab

### LINKED ISSUE #95: Make separate sections for tasks to do and tasks completed
**Is your feature request related to a problem? Please describe.**
The tasks section is not organized to show completed tasks and yet to complete tasks.

**Describe the solution you'd like**
There should be two sections/drop sections to show to-do tasks and completed tasks separately. Just like in Android version of Mentorship.

**Additional context**
Android version: 

Flutter version:

### PR DESCRIPTION
**Pull request by bharat-1809**
### Description
This PR adds sections in the task tab of the relations page. To-do and achieved tasks are separated using an expandable panel.

Fixes #95 

### Flutter Channel:
- [ ] I have used the Flutter Beta channel on my local machine 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
This is tested on a physical device.

Steps: 
- Goto Relations Page
- Click on the Tasks Tab

Here is a working demo of the same

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by techno-disaster — APPROVED** [review]
LGTM

**Comment by techno-disaster** [comment]
@anitab-org/qa-team can someone test this?

**Comment by isabelcosta** [comment]
@bharat-1809 can you please fix the merge conflict here so we can review this again and merge once approved?

**Comment by bharat-1809** [comment]
@isabelcosta Sure!

**Comment by bharat-1809** [comment]
@isabelcosta I have resolved the conflicts!

**Review by isabelcosta — APPROVED** [review]
Looks good 👍

**Comment by isabelcosta** [comment]
@Techno-Disaster can you test this and show the proof here please :) If you feel this is working as expected then feel free to merge

**Comment by techno-disaster** [comment]
Ok, Ill test this. i guess i need to update docs on the artifacts thingy asap. https://github.com/anitab-org/mentorship-flutter/pull/130/checks

**Review by robotjellyzone — APPROVED** [review]
I have tested this pr and its working in the way it should 👍 .
The changes made in this PR were tested locally. Following are the results:

1. Code Review: Done

2. All possible responses were tested as below:
Screenshot/gif:

sectionsTaskTested

Expected Result: adding sections in the task tab
Actual Result: Same as above

3. Additional testcases covered: n/a
4. Device : PIXEL XL API 27

**Comment by isabelcosta** [comment]
@robotjellyzone thank you so much for your help testing this PR 🙌

**Pull request merged**
