### PR TITLE
Updated all dependencies

### PR DESCRIPTION
**Pull request by bartekpacia**
### Overview 
I updated all dependencies to their newest possible versions.

### Tests
Tested on Android emulator (Pixel 3a API 29), all features work fine.

### CODE REVIEW

**Comment by techno-disaster** [comment]
@bartekpacia did you request review manually or did it come automatically? just need to check if codeownenrs is working

**Comment by bartekpacia** [comment]
@Techno-Disaster No, I didn't do anything to check if your feature is working :) Nice!

**Comment by techno-disaster** [comment]
so codeowners is working too cools.

**Comment by techno-disaster** [comment]
@bartekpacia check the build status, this is the reason i was trying to avoid pubspec.lock, any idea why this errors occurs? i could remove git diff --exit code and this will pass tho

**Comment by bartekpacia** [comment]
@Techno-Disaster I think you have setup the GitHub build actions wrong, because *everything works fine on my machine* and I made pretty typical changes.

**Comment by techno-disaster** [comment]
you can check this run https://github.com/Techno-Disaster/mentorship-flutter/pull/7/checks i changed the pubspec.lock value here too but no git diff error

**Comment by techno-disaster** [comment]
@bartekpacia yes the app is built completely, if you see the logs flutter build apk was completed successfully, where we get an error is git diif --exit code

**Comment by bartekpacia** [comment]
So maybe just remove this `git diff --exit code`? What is it for?

I have totally no experience with GitHub actions and CI/CD for Flutter 🙄 So I can't really help you with this.

**Comment by techno-disaster** [comment]
@bartekpacia i made this as a precaution so that people don't mess up the pubspec.lock file with different versions. I think i should remove it.

**Comment by bartekpacia** [comment]
@Techno-Disaster looks like you forgot to delete `git diff --exit code` from iOS build.

**Comment by techno-disaster** [comment]
@bartekpacia really sorry, the PR is up already

**Comment by techno-disaster** [comment]
@bartekpacia side note: you don't have to always push a change to trigger the action you can go to the previous run where it failed and there is a option to re-run all the jobs in the top right corner

**Comment by bartekpacia** [comment]
@Techno-Disaster thanks! didn't know that

**Comment by techno-disaster** [comment]
@bartekpacia checks seem good to go now thanks for helping me test them

**Review by techno-disaster — APPROVED** [review]

**Review by isabelcosta — APPROVED** [review]

**Pull request merged**
