### PR TITLE
Fix members page reload

### LINKED ISSUE #115: feat: let user refresh page even if they reach the end
**Is your feature request related to a problem? Please describe.**
I cant refresh the members page when I reach the end

**Describe the solution you'd like**
User should be able to refresh the page even if he/she has reached the end

### PR DESCRIPTION
**Pull request by techno-disaster**
## Description
User should be able to refresh the page even if he/she has reached the end

Fixes #115 

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Physical device

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by bartekpacia — APPROVED** [review]

**Comment by isabelcosta** [comment]
@Techno-Disaster I see no issue for this 🤷‍♀️ Is there one for this?

**Comment by techno-disaster** [comment]
no it was a really small change 🙈. Will create one asap

**Comment by isabelcosta** [comment]
@Techno-Disaster once created you can link it in this PR description with 
`Fixes ###`

**Comment by techno-disaster** [comment]
@isabelcosta done :)

**Review by isabelcosta — APPROVED** [review]

**Comment by isabelcosta** [comment]
@Techno-Disaster I asked for someone to test the PR and assigned the label, I have seen no confirmation that this was working. Please remember to follow our guidelines. cc @anitab-org/qa-team

**Comment by HaripriyaB** [comment]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Before_  
     
Record-2020-07-26-12-50-47-92746

  * _After_ 
   
20200726-124807-720x1440

    _Expected Result_:  Refresh function, after full list of members is fetched, works fine 
    _Actual Result_:  As expected
    
3. Status of PR Changed to: Merged ✔️

**Comment by techno-disaster** [comment]
> @Techno-Disaster I asked for someone to test the PR and assigned the label, I have seen no confirmation that this was working. Please remember to follow our guidelines. cc @anitab-org/qa-team

oh, i honestly didn't see the needs testing badge. Also don't we usually do 1 code review then 1 testing and then the last code review and then the merge button is enabled? Missed the badge , won't happen again.

**Pull request merged**
