### PR TITLE
docs: remove travis "master" build status

### LINKED ISSUE #53: Remove Travis "master" branch status
**Describe the bug**
 PR #52 added travis build status badges, but it also included the badge for "master" branch which we will not be using atm and hence we have to remove it

**Expected behavior**
Have only "develop" branch build status in readme.

### PR DESCRIPTION
**Pull request by techno-disaster**
### Description
Removed the travis "master" build status from readme as we will not be using that branch.

Fixes #53 

### Type of Change:

- Documentation

### How Has This Been Tested?
Checked readme

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Sounds good :D @Techno-Disaster

**Comment by isabelcosta** [comment]
Although this branch will become active once we start putting this in production @Techno-Disaster , right?

**Comment by techno-disaster** [comment]
> Although this branch will become active once we start putting this in production @Techno-Disaster , right?

Not sure abt that. but it seems right. keep developing on develop and push to master when we want to release an update

**Review by bartekpacia — APPROVED** [review]
I trust in your good motives @Techno-Disaster ;) and agree on this.

**Pull request merged**
