### PR TITLE
Guide for testing team!

### LINKED ISSUE #141: Add docs for testing team
Recently a PR was merged which was supposed to ease out testing apks, without Android Studio, but most people are unaware about this. We need to create a doc which tells more about this feature. More info [here](https://github.com/anitab-org/mentorship-flutter/pull/126)

### PR DESCRIPTION
**Pull request by rohankumawat**
# Description
As described in Issue no. 141, I took screenshots of how to test a particular PR by using apks instead of Android Studio. Uploaded the screenshots in docs/images/testing and created the markdown file in docs/ folder.

Fixes #141 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by techno-disaster — APPROVED** [review]
Fixed and LGTM

**Comment by techno-disaster** [comment]
@anitab-org/qa-team please check how [this](https://github.com/rohankumawat/mentorship-flutter/blob/testing-guide-branch/docs/testing-guide.md) is and add any suggestions if required

**Review by rpattath — COMMENTED** [review]
Would it be better to upload the screenshots to the issue as a comment and then use the links from there, rather than uploading them under the repo?

**Comment by rohankumawat** [comment]
> Would it be better to upload the screenshots to the issue as a comment and then use the links from there, rather than uploading them under the repo?

Ah! It would be better maybe but I don't know how to do so and when an issue is closed, we can still use the links? 
Till now I've been using the links by uploading them in the repo itself. I created another folder in the docs/images and then uploaded the screenshots as I thought that it already had an images folder in the docs folder.
If you want me to upload the screenshots on an issue and then use them as links, can you just give me a gist about it?
Thank you 😄 .

**Comment by rohankumawat** [comment]
Hi, is this going to be checked? Is something wrong?

**Review by rpattath — COMMENTED** [review]
Yes the issue and the links will not go away. It would be great if you could make that change.

**Comment by techno-disaster** [comment]
@rohankumawat any updates?

**Comment by rohankumawat** [comment]
> @rohankumawat any updates?

I'll do it soon as my exams came but I want to ask this thing that I only have to upload the images as an issue first. Then use those links to do the respective task or use the links in the README.md file. Is that how I'm supposed to do?

**Comment by techno-disaster** [comment]
> > @rohankumawat any updates?
> 
> I'll do it soon as my exams came but I want to ask this thing that I only have to upload the images as an issue first. Then use those links to do the respective task or use the links in the README.md file. Is that how I'm supposed to do?

yep

**Comment by rohankumawat** [comment]
> > > @rohankumawat any updates?
> > 
> > 
> > I'll do it soon as my exams came but I want to ask this thing that I only have to upload the images as an issue first. Then use those links to do the respective task or use the links in the README.md file. Is that how I'm supposed to do?
> 
> yep

And I should create another pull request, right?

**Review by bartekpacia — APPROVED** [review]
Nice work. Thanks!🎉

**Pull request merged**
