### PR TITLE
feat: Add Splash Screen

### LINKED ISSUE #50: Add Splash Screen
**Is your feature request related to a problem? Please describe.**
We see a black screen for the first 2-3 sec when we open the app. The Android version has a splash screen (mentorship logo) which prevents this. 

**Describe the solution you'd like**
Add a Splash screen and a  circular loading indicator below it, to let the app start.

### PR DESCRIPTION
**Pull request by techno-disaster**
### Description
This PR adds a splash screen just like the android version, to remove the black screen when opening. 
Dependencies added > flutter native spash screen

Fixes #50 

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested on physical device

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by bartekpacia — APPROVED** [review]
nice job :)

**Comment by isabelcosta** [comment]
@Techno-Disaster @bartekpacia is the GIF really fast, or the splash screen can barely be seen?

**Comment by bartekpacia** [comment]
@isabelcosta It's just the fast emulator. @Techno-Disaster could record the GIF on a slower phone (I think it can be simulated in the emulator settings) but it's okay IMO.

**Comment by techno-disaster** [comment]
@isabelcosta it's on my physical device. Sorry I can't run an emulator, my laptop hardware is really bad. But yes the gif is at orginal speed and not fast forwarded

**Comment by techno-disaster** [comment]
As the spash screen is generated natively the time for which it appears on a device varies upon its hardware. A slower phone will have a longer spash screen to help startup the app and a smaller splash screen for a faster device

**Comment by isabelcosta** [comment]
I trust you both on this @Techno-Disaster @bartekpacia :)

**Review by isabelcosta — APPROVED** [review]
Seems good :)

**Comment by techno-disaster** [comment]
> I trust you both on this @Techno-Disaster @bartekpacia :) 

Thank you. 🙂

**Pull request merged**
