### PR TITLE
feat: add RadioButtons on SignUp Page

### LINKED ISSUE #59: Single option mentorship availabiliy at Sign Up
## Description

As a user just signing up,
I need a clear definition of the roles I can have in the app,
so that I can start benefiting from the app.

Android app already has this option, so you can follow it.

## Screenshots of the issue

Android version:

android version of this issue

Flutter version:

flutter out dated version

### Update [Required]
- [ ] Make the mentorship availability at sign up single option

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
🤷‍♀️

### PR DESCRIPTION
**Pull request by techno-disaster**
### Description
Added a Both checkbox on signup page for user convience. All edge cases have been tested, check video below.
Fixes #59

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**

- User Interface

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Physical device
Was a really big video (github dosen't allow mp4 only gifs for some reason) so uploaded it to youtube here.
[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=KL_i0xLLodM)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by techno-disaster** [comment]
@anitab-org/qa-team can someone test this? 
Steps:
Register and select mentor or mentee while registering (i have already done a video for both)
check if your profile actually registers with what you have selected

**Review by foongminwong — APPROVED** [review]
The changes made in this PR was tested locally. Following are the results:

1. Code review - Done
2. All possible responses were tested as below:

  * Register as a Mentor
    _Screenshot/gif/video_: https://www.youtube.com/watch?v=3GYHf0aFKy4
    _Expected Result_: A user registers succesfully as a mentor and the profile will have `Available to mentor` checked.
    _Actual Result_: Same as expected result.

  * Register as a Mentee
    _Screenshot/gif/video_: https://www.youtube.com/watch?v=ADBDA7hQJ3M
    _Expected Result_: A user registers succesfully as a mentee and the profile will have `Needs mentoring` checked.
    _Actual Result_:  Same as expected result.
  

  * Register as Both
    _Screenshot/gif/video_: https://www.youtube.com/watch?v=DkbZQ-MVI98
    _Expected Result_: A user registers succesfully as both and the profile will have `Available to mentor` and  `Needs mentoring` checked.
    _Actual Result_:  Same as expected result.

    
3. Additional testcases covered: N/A
    
4. Additional Comments: N/A

5. Status of PR Changed to: `Ready to Merge`

**Comment by bartekpacia** [comment]
@Techno-Disaster If you want to easily convert `.mp4` to `.gif`, you can use `ffmpeg`. Take a look at it. If you have it, all that creating a gif takes is running (assuming you have a video file called `demo.mp4`:
`ffmpeg -i demo.mp4 -filter:v demo.gif`

BTW I think it^ can be added to CONTRIBUTING.

**Comment by isabelcosta** [comment]
@foongminwong your test report is amazing 👏 🎉 @rpattath template looks soooo good here 😄 Thank you so much for doing this!

**Review by isabelcosta — APPROVED** [review]
Based on @foongminwong test report I approve this functionality.
Thank you @Techno-Disaster for working on this.

**Comment by techno-disaster** [comment]
> Based on @foongminwong test report I approve this functionality.
> Thank you @Techno-Disaster for working on this.

@isabelcosta we have a small conflict on #59 can you check it out?

**Comment by isabelcosta** [comment]
@Techno-Disaster @bartekpacia  the conflict was solved with this vote here https://anitab-org.zulipchat.com/#narrow/stream/216323-design/topic/Mentorship.20System.20-.20Redesign/near/198483597

**Review by bartekpacia — APPROVED** [review]
GJ

**Pull request merged**
