### PR TITLE
docs: update commit message link

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [ISSUE]

### Flutter Channel:
- [ ] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by techno-disaster — APPROVED** [review]
Oh, missed this.  👍

**Comment by isabelcosta** [comment]
I will close! this was for demonstration @Techno-Disaster :P for the intro to open source

**Comment by techno-disaster** [comment]
But this isn't this a valid PR @isabelcosta  🤔

**Comment by isabelcosta** [comment]
thank you for the approval however @Techno-Disaster

**Pull request closed without merging**
