### PR TITLE
Fixed some minor warnings + code style suggestion

### PR DESCRIPTION
**Pull request by bartekpacia**
### Description
I fixed some warnings raised by the linter. Mainly:

- `'subtitle' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is subtitle2. This feature was deprecated after v1.13.8..
Try replacing the use of the deprecated member with the replacement.`
Replaced all such usages of 2014-spec with respective 2018 versions.

- `Close instances of 'dart.core.Sink'.`
This is a false positive, as [described here](https://github.com/felangel/bloc/issues/587). I suggest **enforcing people to put linter exception rule before such a safe usage of BLOC.** (below):
```dart
//ignore: close_sinks
SendRequestBloc bloc = BlocProvider.of<SendRequestBloc>(context);
```
This way, we'll have safe, false positives suppressed, but still get lint for any future non-BLOC related usages of Dart Stream API.

- Also, removed all unused imports

### First code style rules
Although [`dartfmt`](https://dart.dev/tools/dartfmt) does a lot of work already, we need even stricter rules to maintain consistent style in the future. 

I suggest:
- **Column line width set to 100**. 80 is simply too small.
This can be easily set in Android Studio/IntelliJ Dart code style settings tab (example below):
Screenshot 2020-04-17 at 12 09 28 AM

In VSCode you have open settings and set Dart: Line Length to 100 (example below):
Screenshot 2020-04-17 at 12 06 30 AM

- **Enforcing the aforementioned use of //ignore: close_sinks in context of safe usages of BLOCs**

This is just a draft, but if we agree on this, I'll update README with the style guide info.

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
All features work fine on Pixel 3a (API 29) emulator.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by techno-disaster** [comment]
warning: [options] target value 7 is obsolete and will be removed in a future release any idea why these warnings pop up?

**Comment by techno-disaster** [comment]
i have never used ignore: close_sinks before so i'm not sure if they block only false positives. If this is not really big change i would keep the ignore: close_sinks commented out for now.What do you think @bartekpacia

**Comment by bartekpacia** [comment]
@Techno-Disaster this probably comes from some native Android libraries (as those warnings are not present on iOS build logs).
Also `// ignore: close_sinks` has to be commented, because, well, it's a comment. I want this to be used only in specific use-cases like assigning BLOC to the variable for pure convenience. Having 10 false positives on Lint really makes it irritating.

I recommend reading https://github.com/felangel/bloc/issues/587 because it  describes it very well (look at comments with high reaction count).

**Comment by techno-disaster** [comment]
ah kk thanks for the info, my bloc knowledge isn't that good as i have used it only 1-2 times till now, will learn it asap

**Review by techno-disaster — APPROVED** [review]

**Comment by bartekpacia** [comment]
@Techno-Disaster no problem, take your time :) I recommend [BLOC crash course by ResoCoder](https://www.youtube.com/watch?v=hTExlt1nJZI), this guy has a lot of quality content.

I also believe that if somebody submits a PR where he will use `//ignore: close_sinks` incorrectly, we will see that and point it out. But it shouldn't ever happen because it's just one specific situation where such `ignore comments` should be put.

**Comment by techno-disaster** [comment]
thanks for the resources @bartekpacia , will start there

**Pull request merged**
